version: '3.8'
services:   
    backend:
        build:
            context: backend
        container_name: expressjs-server
        restart: always
        ports:
            - '80:80' 
        volumes:
            - ./backend/src:/app/src
            - server-node_modules:/usr/src/app/node_modules
        command: npx nodemon -L --config nodemon.json
    client:
        build:
            context: client
        container_name: nextjs-client
        ports:
            - "5173:5173"
        depends_on:
            - backend
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
volumes:
  server-node_modules:
  client-node_modules: